version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "vue",
    "react"
  ]
  environment = [
    "nodejs",
    "browser",
    "vitest",
    "jest"
  ]

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "yapf"

[[code_formatters]]
name = "autopep8"

[[code_formatters]]
name = "ruff"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "prettier"